version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      container_name: postgres-local
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - 5432:5432
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: 123456
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      container_name: keycloak-local
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: 123456
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: 123456
      ports:
        - 8080:8080
      depends_on:
        - postgres
  spring-keycloak-service:
    image: tugayesilyurt/spring-keycloak-service
    container_name: spring-keycloak-service
    build: 
       context: ./spring-keycloak-service
       dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - keycloak
      - postgres